dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
      secure: EwY70tnAecIFoqJ92WZLzXPDJmfDSiHvMPkbaQpb73aLXO3BgrkTGRXYT9AjgX59inaGrtVvp+EQEJfsiQqX1eog70Su8N3Wc6KOLrOy3cP53sGJepC2Fv/RxGLagxWODh79x0wrRpTpcZ8dc2W5HDPUb/WtLlQN2kfg7OAY7b8CQail6uRBTMBED24c+erTa7a0zwIoUr3BTjVZFBR0sOVpHdd4axe54wkTameMOzHObq85f5K1KmNd63/Nq3qm83wDuib9ZFaXR2aqFA4VD+bfZQuH3UJpIPtybUA65i6CjNS9h0ErW9gVKwjBixbZVU95H6SGDd6PWN6Ng0C+SepP1ejG/b8RXI42DBoheJEh9/R3DxKp1kBAi1CO2EEnkAientqBxHZeIrQhJms4brONoygtfRvWejd9a9phIgr1TCA0znQL+pbPc+Ehm6usb+ewh4iXgtHFV/lPP8pwFs3SaL7hDmWLY3Jt/jKnYE+QgG4ZaQA8MbjqwM+2rirXu4iDbD7fdvywLebkm5HOtSKKbcAgSP3OiqN5HZUUbN+H8+sj2U0kFPNymWQwgS8rOI4JG9sN+fLTz5IrdJG0ly43p4WwHtGDq6ZaKaCUXh65JtWJbSq41oJOd48+lq7XHvPI1fVJ4naEfMDUn5H5QWiW4pPwRkTLuxBImou+kcY=
    template:
    - ":hammer_and_wrench: Build <%{build_url}|#%{build_number}> %{result} in %{duration}\n :octocat: <https://www.github.com/%{repository_slug}/tree/%{branch}|%{repository_slug}@%{branch}> in PR <%{pull_request_url}|#%{pull_request_number}>\n:scroll: (<%{compare_url}|%{commit}>) - _%{commit_message}_\n:godmode: %{author}"
